liip_imagine :
    resolvers:
        default :
            web_path : ~

    filter_sets :
        cache : ~

        # the name of the "filter set"
        monFiltre :

            # adjust the image quality to 75%
            quality : 75